modLoader="javafml"
loaderVersion="[47,)"

license="CC BY-NC-SA 3.0"
issueTrackerURL=""

[[mods]]
	modId="tagtooltips"
	version="1.20.1-1.0"
	displayName="Tag Tooltips"
	displayURL=""
	authors="Jagm"
	description="Hold semicolon to view item tags."
	
[[dependencies.tagtooltips]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.tagtooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"